spring:
  application:
    name: file-processing-service

  datasource:
    url: jdbc:postgresql://localhost:5432/fileprocessing
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  port: 8080